name: chatService
endpoints:
  -
    name: CreateUser
    args: user User
    output: id string
    transport: 
      method: POST
      path: /user
  -
    name: GetUser
    args: id string 
    output: user User
    transport:
      method: GET
      path: /user/{id}
  -
    name: UpdateUser
    args: id string, profilePic string
    output: message string
    transport:
      method: PUT
      path: /user/update
      
repository: true


model:
  -
    name: User
    attr: firstName string, lastName string , profilePic string , token string

  


  

