name: userService
redis_cache:
  host: host
  password: password
  db: 0

endpoints:
  -
    name: CreateUser
    args: 
      - user User
    output: 
      - id string
    transport: 
      method: POST
      path: /user
  -
    name: GetUser
    args: 
      - id string
    output: 
      - user User
    cache_time: 10000
    transport:
      method: GET
      path: /user/{id}
  -
    name: UpdateUser
    args: 
      - id string
      - profilePic string
    output: 
      - message string
    transport:
      method: PUT
      path: /user/update
  -
    name: GetAllUsers
    args:
    output: 
      - users []User
    cache_time: 10000
    transport:
      method: GET
      path: /user
  
repository:
  value: true
  db:
    name: mysql
    address: address

model:
  -
    name: User
    attr: 
      - firstName string 
      - lastName string  
      - profilePic string 
      - token string